### ISSUE TITLE
number.py not in pip install package

### ISSUE THREAD

**Issue by jgalak** [hayj/SystemTools#1]
Just what the header says.  I did a "pip install hjsystemtools", which succeeded, but number.py is not in the directory.  Other files (basics.py, duration.py, etc. are there).

Python 3.6.5, pop 10.0.1

**Comment by hayj** [comment]
Now it works, I forgot to push on PyPi, thank you!

**Comment by hayj** [comment]
I had to do this:

```bash
pip uninstall hjsystemtools
pip install --no-cache-dir -v hjsystemtools
```
