### ISSUE TITLE
systools 0.0.95 error when install on windows

### ISSUE THREAD

**Issue by ftesser** [hayj/SystemTools#4]
When I try to install the package on Windows  with:

```bash
pip install systools
```
I obtained this error:
```
ERROR: Requested systools from https://files.pythonhosted.org/packages/46/b3/c1424b2c888d04cdb18c58b1a32665a5f6c7bef1430b17c1bd618ca4c17f/systools-0.0.95.tar.gz#sha256=2aaf155f5e487f802e59c91aeaf46bd87
c2bca64b83671958e8554ab8bf392a2 has different version in metadata: '0.0.92'
```
I did not obtain the error in Linux.

**Comment by ftesser** [comment]
Additional comments: is the pypi package synchronised with this project?
I see that sometime is mentioned https://pypi.org/project/systools/  and sometimes https://pypi.org/project/hjsystemtools/
Is the code of https://pypi.org/project/systools/  0.0.95 the same that is in the master of this project?

If so, I thik should be better to tag the code when a new release is delivered to pypi.

**Comment by hayj** [comment]
Thx for your advices. I created a new release and pushed on github and pypi.
(Didn't test on windows sorry)

**Comment by ftesser** [comment]
Great, now it works also on Windows:
```bash
Installing collected packages: systools
Successfully installed systools-0.1.0
```

Thanks for your package!
